// <auto-generated />
using BianchiJacopoProvaVerifica2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BianchiJacopoProvaVerifica2.Migrations
{
    [DbContext(typeof(RomanziContext))]
    [Migration("20241121171721_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Autore", b =>
                {
                    b.Property<int>("AutoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazionalità")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutoreId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Personaggio", b =>
                {
                    b.Property<int>("PersonaggioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RomanzoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaggioId");

                    b.HasIndex("RomanzoId");

                    b.ToTable("Personaggi");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Romanzo", b =>
                {
                    b.Property<int>("RomanzoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoPubblicazione")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RomanzoId");

                    b.HasIndex("AutoreId");

                    b.ToTable("Romanzi");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Personaggio", b =>
                {
                    b.HasOne("BianchiJacopoProvaVerifica2.Model.Romanzo", "Romanzo")
                        .WithMany("Personaggi")
                        .HasForeignKey("RomanzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Romanzo");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Romanzo", b =>
                {
                    b.HasOne("BianchiJacopoProvaVerifica2.Model.Autore", "Autore")
                        .WithMany("Romanzi")
                        .HasForeignKey("AutoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autore");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Autore", b =>
                {
                    b.Navigation("Romanzi");
                });

            modelBuilder.Entity("BianchiJacopoProvaVerifica2.Model.Romanzo", b =>
                {
                    b.Navigation("Personaggi");
                });
#pragma warning restore 612, 618
        }
    }
}
